package com.sakib_jeter.backend.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import com.sakib_jeter.backend.entity.Account;

public interface AccountRepository extends JpaRepository<Account, Long> {
    Account findByUserId(Long userId);// Implementation generated by jpa query methods equaivalent to select *
                                      // from accounts where user_id = userId
}