services:
  mysql:
    image: mysql:8
    container_name: financedb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: financeDb
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - financeDb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      cache_from:
        - papertrade-backend:latest
    image: papertrade-backend:latest
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/financeDb?createDatabaseIfNotExist=true
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FINNHUB_KEY: ${FINNHUB_KEY}
      FMP_KEY: ${FMP_KEY}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL}
      cache_from:
        - papertrade-frontend:latest
    image: papertrade-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  financeDb:
    name: financeDb