spring.config.import=optional:file:.env[.properties]

spring.application.name=backend
server.port=8080


# Database - Pulls from .env or OS environment
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# API Keys - Pulls from .env or OS environment
finnhub.api.key=${FINNHUB_KEY}
finnhub.base.url=https://finnhub.io/api/v1

# Swagger/Docs
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

# External Services
yahoo.base.url=https://query1.finance.yahoo.com/v8/finance/chart
yahoo.interval=1year
fmp.api.key=${FMP_KEY}
fmp.base.url=https://financialmodelingprep.com/stable