spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/financeDb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

finnhub.api.key=d6r24g1r01qgdhqcsf8gd6r24g1r01qgdhqcsf90
finnhub.base.url=https://finnhub.io/api/v1

server.port=8080

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs

yahoo.base.url=https://query1.finance.yahoo.com/v8/finance/chart
yahoo.interval=1year

fmp.api.key=o5q3EhCj0Z284J42IgyQ91gg2VD1DJ4z
fmp.base.url=https://financialmodelingprep.com/stable
