spring.config.import=optional:file:.env[.properties]

spring.application.name=backend
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Swagger/Docs
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
server.forward-headers-strategy=framework

# API Keys
finnhub.api.key=${FINNHUB_KEY}
finnhub.base.url=https://finnhub.io/api/v1
fmp.api.key=${FMP_KEY}
fmp.base.url=https://financialmodelingprep.com/stable

# External Services
yahoo.base.url=https://query1.finance.yahoo.com/v8/finance/chart
yahoo.interval=1year

# Dev
spring.devtools.add-properties=false
logging.level.root=WARN